site_name: Danske Meshtastic Brugere
site_description: Flesskab for danske brugere af Meshtastic
site_url: https://meshbrugere.dk
site_author: Meshbrugere.dk
repo_url: https://github.com/danske-meshtastic-brugere/meshbrugere.dk
repo_name: GitHub

theme:
  name: simplex  # Bootswatch Simplex-tema
  language: da
  locale: da

nav:
  - Forside: index.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/meshbrugere/meshbruger.dk
      name: GitHub

