site_name: Danske Meshtastic Brugere
site_description: Flesskab for danske brugere af Meshtastic
site_url: https://meshbrugere.dk
site_author: Meshbrugere.dk
repo_url: https://github.com/Danske-Meshtastic-Brugere/meshbrugere.dk
edit_uri: edit/main/docs/
repo_name: GitHub

theme:
  name: cinder # Bootswatch Simplex-tema
  language: da
  locale: da
  custom_dir: overrides
nav:
  - Forside: index.md
  - Discord: discord.md
  - Om: om.md
  - Begynder Tips: tips.md
